spring:
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
      enabled: true
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

  jwt:
    secret: ${JWT_SECRET}
    authorities_key: auth
    bearer-type: Bearer
    access-token-expire-time: 864000000 # 10 days in milliseconds

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope: email, profile

server:
  port: ${SPRING_PORT}
  servlet:
    encoding:
      charset: utf-8

endpoints:
  breed-detect: http://host.docker.internal:5000/predict_breed
  weight-detect: http://host.docker.internal:5000/predict_weight

logging:
  level:
    org:
    hibernate:
      SQL: DEBUG
    type:
      descriptor:
        sql:
          BasicBinder: TRACE
